// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hmxraezyquqslkolaqmk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhteHJhZXp5cXVxc2xrb2xhcW1rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyODYxNDEsImV4cCI6MjA3Mzg2MjE0MX0.qQRFdaOR1J0RC7ibCm8N78i1Y_K81MndSuhVyOSw1Qk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});